keys:
  - &kasbjornsen age1vktgrvlss5ru0588p3cgdvz026lqxetdc56fv42z9a5903t5mgqsufe6lf 
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kasbjornsen
