keys:
  - &kasbjornsen age1vktgrvlss5ru0588p3cgdvz026lqxetdc56fv42z9a5903t5mgqsufe6lf
  - &odin age1gqnuns9cf4lvj5uj6k7e5uxls9h7gqheg2ay2xjnrr00fzdxk3yssrltj3
creation_rules:
  - path_regex: private.yml$
    key_groups:
    - age:
      - *kasbjornsen
      - *odin
