keys:
  - &kasbjornsen age15z4pugmy244zqwrks7sq5r9jzrhnj4r9dkgcfqsdj223s854qffqeemrrz
  - &odin age1gqnuns9cf4lvj5uj6k7e5uxls9h7gqheg2ay2xjnrr00fzdxk3yssrltj3
creation_rules:
  - path_regex: private.yml$
    key_groups:
    - age:
      - *kasbjornsen
      - *odin
