keys:
  - &kasbjornsen 06FF317D861507E6
  - &odin age1gqnuns9cf4lvj5uj6k7e5uxls9h7gqheg2ay2xjnrr00fzdxk3yssrltj3
creation_rules:
  - path_regex: private.yml$
    key_groups:
    - pgp:
      - *kasbjornsen
    - age:
      - *odin
